fn source(id: ThemeId) -> SourceTheme {
    match id {
        // The fixed Cyril Dark palette: fixed brightened RGB held to per-tier WCAG targets (ADR 0007, tests::cyril_dark_contrast_contract).
        ThemeId::CyrilDark => SourceTheme {
            syntax: SyntaxTheme::Base16EightiesDark,
            canvas: SourceColor::Reset,
            chrome: SourceColor::Rgb(0x1e, 0x1e, 0x2e),
            code: SourceColor::Rgb(0x28, 0x2c, 0x34),
            selection: SourceColor::Rgb(0x32, 0x32, 0x46),
            text: SourceColor::Rgb(0xff, 0xff, 0xff),
            muted: SourceColor::Rgb(0x8c, 0x8c, 0x8c),
            border: SourceColor::Rgb(0x8c, 0x8c, 0x8c),
            accent: SourceColor::Rgb(0x00, 0xff, 0xff),
            accent_alt: SourceColor::Rgb(0xb4, 0x8e, 0xad),
            user: SourceColor::Rgb(0x8a, 0xb4, 0xf8),
            agent: SourceColor::Rgb(0x81, 0xc7, 0x84),
            system: SourceColor::Rgb(0xb4, 0x8e, 0xad),
            info: SourceColor::Rgb(0x00, 0xff, 0xff),
            success: SourceColor::Rgb(0x00, 0xff, 0x00),
            warning: SourceColor::Rgb(0xff, 0xff, 0x00),
            danger: SourceColor::Rgb(0xff, 0x00, 0x00),
            diff_add: SourceColor::Rgb(0x00, 0xff, 0x00),
            diff_delete: SourceColor::Rgb(0xff, 0x00, 0x00),
            diff_context: SourceColor::Rgb(0x8c, 0x8c, 0x8c),
            emphasis: SourceColor::Rgb(0xd7, 0xba, 0x7d),
            accent_tertiary: SourceColor::Rgb(0x6c, 0xb6, 0xff),
            accent_quaternary: SourceColor::Rgb(0xcd, 0x9e, 0xe6),
            accent_quinary: SourceColor::Rgb(0x56, 0xc7, 0xd0),
            subdued: SourceColor::Rgb(0x80, 0x80, 0x80),
            subdued_positive: SourceColor::Rgb(0x00, 0x80, 0x00),
            subdued_negative: SourceColor::Rgb(0xd9, 0x8a, 0x8a),
            soft_accent: SourceColor::Rgb(0x8a, 0xb4, 0xf8),
            positive_accent: SourceColor::Rgb(0x81, 0xc7, 0x84),
            inset_background: SourceColor::Rgb(0x28, 0x2c, 0x34),
            text_secondary: SourceColor::Rgb(0xc0, 0xc0, 0xc0),
            accent_violet: SourceColor::Rgb(0xb0, 0x8d, 0xff),
        },
        // Cyril Light: dark foregrounds on a painted light canvas (tier policy: .cyril-fkke/design.md).
        ThemeId::CyrilLight => SourceTheme {
            syntax: SyntaxTheme::Base16OceanLight,
            canvas: SourceColor::Rgb(0xff, 0xff, 0xff),
            chrome: SourceColor::Rgb(0xe8, 0xe8, 0xef),
            code: SourceColor::Rgb(0xf2, 0xf2, 0xf7),
            selection: SourceColor::Rgb(0xd7, 0xd7, 0xe8),
            text: SourceColor::Rgb(0x1c, 0x1c, 0x28),
            muted: SourceColor::Rgb(0x5f, 0x5f, 0x6b),
            border: SourceColor::Rgb(0x6b, 0x6b, 0x78),
            accent: SourceColor::Rgb(0x00, 0x69, 0x7a),
            accent_alt: SourceColor::Rgb(0x7a, 0x3f, 0x7a),
            user: SourceColor::Rgb(0x1a, 0x5f, 0xb4),
            agent: SourceColor::Rgb(0x1a, 0x6b, 0x3a),
            system: SourceColor::Rgb(0x7a, 0x3f, 0x7a),
            info: SourceColor::Rgb(0x00, 0x69, 0x7a),
            success: SourceColor::Rgb(0x15, 0x80, 0x3d),
            warning: SourceColor::Rgb(0x8a, 0x5a, 0x00),
            danger: SourceColor::Rgb(0xb3, 0x26, 0x1e),
            diff_add: SourceColor::Rgb(0x15, 0x80, 0x3d),
            diff_delete: SourceColor::Rgb(0xb3, 0x26, 0x1e),
            diff_context: SourceColor::Rgb(0x5f, 0x5f, 0x6b),
            emphasis: SourceColor::Rgb(0x7a, 0x4f, 0x00),
            accent_tertiary: SourceColor::Rgb(0x0b, 0x5c, 0xad),
            accent_quaternary: SourceColor::Rgb(0x7a, 0x3f, 0x9e),
            accent_quinary: SourceColor::Rgb(0x00, 0x66, 0x6b),
            subdued: SourceColor::Rgb(0x6b, 0x6b, 0x78),
            subdued_positive: SourceColor::Rgb(0x2f, 0x6b, 0x3a),
            subdued_negative: SourceColor::Rgb(0xa0, 0x4a, 0x4a),
            soft_accent: SourceColor::Rgb(0x1a, 0x5f, 0xb4),
            positive_accent: SourceColor::Rgb(0x1a, 0x6b, 0x3a),
            inset_background: SourceColor::Rgb(0xf2, 0xf2, 0xf7),
            text_secondary: SourceColor::Rgb(0x4a, 0x4a, 0x57),
            accent_violet: SourceColor::Rgb(0x6a, 0x3f, 0xb0),
        },
        // High Contrast Dark: AAA targets (>=7.0 primary, >=4.5 muted) on a painted black canvas.
        ThemeId::HighContrastDark => SourceTheme {
            syntax: SyntaxTheme::Base16OceanDark,
            canvas: SourceColor::Rgb(0x00, 0x00, 0x00),
            chrome: SourceColor::Rgb(0x00, 0x00, 0x00),
            code: SourceColor::Rgb(0x10, 0x10, 0x10),
            selection: SourceColor::Rgb(0x00, 0x40, 0x5a),
            text: SourceColor::Rgb(0xff, 0xff, 0xff),
            muted: SourceColor::Rgb(0xc0, 0xc0, 0xc0),
            border: SourceColor::Rgb(0xc0, 0xc0, 0xc0),
            accent: SourceColor::Rgb(0x00, 0xff, 0xff),
            accent_alt: SourceColor::Rgb(0xff, 0x9e, 0xf5),
            user: SourceColor::Rgb(0x7f, 0xb3, 0xff),
            agent: SourceColor::Rgb(0x7f, 0xff, 0xa0),
            system: SourceColor::Rgb(0xff, 0xa0, 0xff),
            info: SourceColor::Rgb(0x00, 0xff, 0xff),
            success: SourceColor::Rgb(0x00, 0xff, 0x00),
            warning: SourceColor::Rgb(0xff, 0xff, 0x00),
            danger: SourceColor::Rgb(0xff, 0x80, 0x80),
            diff_add: SourceColor::Rgb(0x00, 0xff, 0x00),
            diff_delete: SourceColor::Rgb(0xff, 0x80, 0x80),
            diff_context: SourceColor::Rgb(0xc0, 0xc0, 0xc0),
            emphasis: SourceColor::Rgb(0xff, 0xe0, 0x66),
            accent_tertiary: SourceColor::Rgb(0x8a, 0xb4, 0xff),
            accent_quaternary: SourceColor::Rgb(0xe0, 0xa0, 0xff),
            accent_quinary: SourceColor::Rgb(0x66, 0xe0, 0xe0),
            subdued: SourceColor::Rgb(0xb0, 0xb0, 0xb0),
            subdued_positive: SourceColor::Rgb(0x7f, 0xff, 0xa0),
            subdued_negative: SourceColor::Rgb(0xff, 0x9e, 0x9e),
            soft_accent: SourceColor::Rgb(0x7f, 0xb3, 0xff),
            positive_accent: SourceColor::Rgb(0x7f, 0xff, 0xa0),
            inset_background: SourceColor::Rgb(0x10, 0x10, 0x10),
            text_secondary: SourceColor::Rgb(0xd0, 0xd0, 0xd0),
            accent_violet: SourceColor::Rgb(0xc9, 0xa7, 0xff),
        },
        // High Contrast Light: AAA targets on a painted white canvas.
        ThemeId::HighContrastLight => SourceTheme {
            syntax: SyntaxTheme::InspiredGitHub,
            canvas: SourceColor::Rgb(0xff, 0xff, 0xff),
            chrome: SourceColor::Rgb(0xf0, 0xf0, 0xf0),
            code: SourceColor::Rgb(0xf0, 0xf0, 0xf0),
            selection: SourceColor::Rgb(0xc8, 0xdc, 0xf0),
            text: SourceColor::Rgb(0x00, 0x00, 0x00),
            muted: SourceColor::Rgb(0x44, 0x44, 0x44),
            border: SourceColor::Rgb(0x44, 0x44, 0x44),
            accent: SourceColor::Rgb(0x00, 0x4f, 0x66),
            accent_alt: SourceColor::Rgb(0x6a, 0x1f, 0x6a),
            user: SourceColor::Rgb(0x0a, 0x3f, 0x8f),
            agent: SourceColor::Rgb(0x0a, 0x4a, 0x1f),
            system: SourceColor::Rgb(0x6a, 0x1f, 0x6a),
            info: SourceColor::Rgb(0x00, 0x4f, 0x66),
            success: SourceColor::Rgb(0x0a, 0x5a, 0x1f),
            warning: SourceColor::Rgb(0x5a, 0x3a, 0x00),
            danger: SourceColor::Rgb(0x8f, 0x1a, 0x12),
            diff_add: SourceColor::Rgb(0x0a, 0x5a, 0x1f),
            diff_delete: SourceColor::Rgb(0x8f, 0x1a, 0x12),
            diff_context: SourceColor::Rgb(0x44, 0x44, 0x44),
            emphasis: SourceColor::Rgb(0x5a, 0x3a, 0x00),
            accent_tertiary: SourceColor::Rgb(0x0a, 0x3f, 0x8f),
            accent_quaternary: SourceColor::Rgb(0x6a, 0x1f, 0x6a),
            accent_quinary: SourceColor::Rgb(0x00, 0x4f, 0x66),
            subdued: SourceColor::Rgb(0x44, 0x44, 0x44),
            subdued_positive: SourceColor::Rgb(0x0a, 0x5a, 0x1f),
            subdued_negative: SourceColor::Rgb(0x8f, 0x1a, 0x12),
            soft_accent: SourceColor::Rgb(0x0a, 0x3f, 0x8f),
            positive_accent: SourceColor::Rgb(0x0a, 0x5a, 0x1f),
            inset_background: SourceColor::Rgb(0xf0, 0xf0, 0xf0),
            text_secondary: SourceColor::Rgb(0x33, 0x33, 0x33),
            accent_violet: SourceColor::Rgb(0x5a, 0x1f, 0xa0),
        },
        // Catppuccin Mocha: upstream Mocha colors adjusted only where a tier required it; Syntect has no Catppuccin component, so base16-mocha.dark is the nearest available syntax theme.
        ThemeId::CatppuccinMocha => SourceTheme {
            syntax: SyntaxTheme::Base16MochaDark,
            canvas: SourceColor::Rgb(0x1e, 0x1e, 0x2e),
            chrome: SourceColor::Rgb(0x18, 0x18, 0x25),
            code: SourceColor::Rgb(0x18, 0x18, 0x25),
            selection: SourceColor::Rgb(0x45, 0x47, 0x5a),
            text: SourceColor::Rgb(0xcd, 0xd6, 0xf4),
            muted: SourceColor::Rgb(0x93, 0x99, 0xb2),
            border: SourceColor::Rgb(0x6c, 0x70, 0x86),
            accent: SourceColor::Rgb(0x89, 0xdc, 0xeb),
            accent_alt: SourceColor::Rgb(0xcb, 0xa6, 0xf7),
            user: SourceColor::Rgb(0x89, 0xb4, 0xfa),
            agent: SourceColor::Rgb(0xa6, 0xe3, 0xa1),
            system: SourceColor::Rgb(0xcb, 0xa6, 0xf7),
            info: SourceColor::Rgb(0x89, 0xdc, 0xeb),
            success: SourceColor::Rgb(0xa6, 0xe3, 0xa1),
            warning: SourceColor::Rgb(0xf9, 0xe2, 0xaf),
            danger: SourceColor::Rgb(0xf3, 0x8b, 0xa8),
            diff_add: SourceColor::Rgb(0xa6, 0xe3, 0xa1),
            diff_delete: SourceColor::Rgb(0xf3, 0x8b, 0xa8),
            diff_context: SourceColor::Rgb(0x93, 0x99, 0xb2),
            emphasis: SourceColor::Rgb(0xf9, 0xe2, 0xaf),
            accent_tertiary: SourceColor::Rgb(0x89, 0xb4, 0xfa),
            accent_quaternary: SourceColor::Rgb(0xcb, 0xa6, 0xf7),
            accent_quinary: SourceColor::Rgb(0x94, 0xe2, 0xd5),
            subdued: SourceColor::Rgb(0x7f, 0x84, 0x9c),
            subdued_positive: SourceColor::Rgb(0x8f, 0xbf, 0x95),
            subdued_negative: SourceColor::Rgb(0xd9, 0x90, 0x9f),
            soft_accent: SourceColor::Rgb(0x89, 0xb4, 0xfa),
            positive_accent: SourceColor::Rgb(0xa6, 0xe3, 0xa1),
            inset_background: SourceColor::Rgb(0x18, 0x18, 0x25),
            text_secondary: SourceColor::Rgb(0xba, 0xc2, 0xde),
            accent_violet: SourceColor::Rgb(0xb4, 0xbe, 0xfe),
        },
        // Gruvbox Dark (medium): upstream Gruvbox colors adjusted only where a tier required it; base16-eighties.dark is the nearest bundled syntax theme.
        ThemeId::GruvboxDark => SourceTheme {
            syntax: SyntaxTheme::Base16EightiesDark,
            canvas: SourceColor::Rgb(0x28, 0x28, 0x28),
            chrome: SourceColor::Rgb(0x1d, 0x20, 0x21),
            code: SourceColor::Rgb(0x32, 0x30, 0x2f),
            selection: SourceColor::Rgb(0x50, 0x49, 0x45),
            text: SourceColor::Rgb(0xeb, 0xdb, 0xb2),
            muted: SourceColor::Rgb(0xa8, 0x99, 0x84),
            border: SourceColor::Rgb(0x92, 0x83, 0x74),
            accent: SourceColor::Rgb(0x8e, 0xc0, 0x7c),
            accent_alt: SourceColor::Rgb(0xd3, 0x86, 0x9b),
            user: SourceColor::Rgb(0x83, 0xa5, 0x98),
            agent: SourceColor::Rgb(0xb8, 0xbb, 0x26),
            system: SourceColor::Rgb(0xd3, 0x86, 0x9b),
            info: SourceColor::Rgb(0x8e, 0xc0, 0x7c),
            success: SourceColor::Rgb(0xb8, 0xbb, 0x26),
            warning: SourceColor::Rgb(0xfa, 0xbd, 0x2f),
            danger: SourceColor::Rgb(0xfb, 0x49, 0x34),
            diff_add: SourceColor::Rgb(0xb8, 0xbb, 0x26),
            diff_delete: SourceColor::Rgb(0xfb, 0x49, 0x34),
            diff_context: SourceColor::Rgb(0xa8, 0x99, 0x84),
            emphasis: SourceColor::Rgb(0xfa, 0xbd, 0x2f),
            accent_tertiary: SourceColor::Rgb(0x83, 0xa5, 0x98),
            accent_quaternary: SourceColor::Rgb(0xd3, 0x86, 0x9b),
            accent_quinary: SourceColor::Rgb(0x8e, 0xc0, 0x7c),
            subdued: SourceColor::Rgb(0x92, 0x83, 0x74),
            subdued_positive: SourceColor::Rgb(0x98, 0x97, 0x1a),
            subdued_negative: SourceColor::Rgb(0xcc, 0x66, 0x66),
            soft_accent: SourceColor::Rgb(0x83, 0xa5, 0x98),
            positive_accent: SourceColor::Rgb(0xb8, 0xbb, 0x26),
            inset_background: SourceColor::Rgb(0x32, 0x30, 0x2f),
            text_secondary: SourceColor::Rgb(0xd5, 0xc4, 0xa1),
            accent_violet: SourceColor::Rgb(0xd3, 0x86, 0x9b),
        },
    }
}
