//! cyril-cc5e regression fences: picker selection visibility (claims C1-C7,
//! C10). Expected drawn-sets are literals generated by the independent
//! arithmetic oracle `.cyril-cc5e/oracle-v2.py` — never recomputed here with
//! the implementation's own formula.

use cyril_core::types::CommandOption;
use cyril_ui::traits::PickerState;
use cyril_ui::widgets::picker;
use ratatui::Terminal;
use ratatui::backend::TestBackend;

fn opts(n: usize) -> Vec<CommandOption> {
    (0..n)
        .map(|i| CommandOption {
            label: format!("opt-{i:02}"),
            value: format!("v{i:02}"),
            description: Some(format!("desc-{i:02}")),
            group: None,
            is_current: i == 0,
        })
        .collect()
}

fn picker_state(options: Vec<CommandOption>, selected: usize) -> PickerState {
    let n = options.len();
    PickerState {
        title: "Fence".into(),
        options,
        filter: String::new(),
        filtered_indices: (0..n).collect(),
        selected,
    }
}

fn render_text(w: u16, h: u16, state: &PickerState) -> String {
    let backend = TestBackend::new(w, h);
    let mut terminal = Terminal::new(backend).expect("terminal");
    terminal
        .draw(|frame| {
            let theme = cyril_ui::theme::resolve(
                cyril_ui::theme::ThemeId::CyrilDark,
                cyril_ui::theme::ColorMode::TrueColor,
            );
            picker::render(frame, frame.area(), state, &theme);
        })
        .expect("draw");
    let buffer = terminal.backend().buffer();
    (0..h)
        .map(|y| {
            (0..w)
                .map(|x| buffer[(x, y)].symbol().chars().next().unwrap_or(' '))
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn drawn_labels(text: &str, n: usize) -> Vec<String> {
    (0..n)
        .map(|i| format!("opt-{i:02}"))
        .filter(|l| text.contains(l.as_str()))
        .collect()
}

fn popup_height(text: &str) -> usize {
    let rows: Vec<&str> = text.lines().collect();
    let Some(top) = rows.iter().position(|r| r.contains('┌')) else {
        panic!("top border missing\n{text}");
    };
    let Some(bottom) = rows.iter().rposition(|r| r.contains('└')) else {
        panic!("bottom border missing\n{text}");
    };
    bottom - top + 1
}

/// C1: for every size/count/selection combination at or above the 60x16
/// floor, the selected option's label and the ▸ marker are on screen.
#[test]
fn selection_always_visible() {
    for &(w, h) in &[(60u16, 16u16), (80, 24), (200, 50)] {
        for &n in &[1usize, 3, 7, 15, 16, 20, 30, 100] {
            for k in [0, n / 2, n - 1] {
                let state = picker_state(opts(n), k);
                let text = render_text(w, h, &state);
                let Some(marker_line) = text.lines().find(|l| l.contains('▸')) else {
                    panic!("no marker at {w}x{h} n={n} k={k}\n{text}");
                };
                assert!(
                    marker_line.contains(&format!("opt-{k:02}")),
                    "marker row is not the selected option at {w}x{h} n={n} k={k}\n{text}"
                );
            }
        }
    }
}

/// C2: the drawn options are exactly the contiguous window the independent
/// oracle predicts (literals from oracle-v2.py), containing the selection.
#[test]
fn window_contiguous_fill() {
    // (n, k, expected window from oracle-v2.py at 80x24)
    let fixtures: &[(usize, usize, std::ops::Range<usize>)] = &[
        (20, 19, 5..20), // F1 tail-clamp: unclamped centering would overflow
        (20, 10, 3..18), // F2 mid
        (16, 15, 1..16), // F3 one past the 15-row cap, pinned to tail
        (1, 0, 0..1),    // F4 single
    ];
    for (n, k, expected) in fixtures {
        let state = picker_state(opts(*n), *k);
        let text = render_text(80, 24, &state);
        let drawn = drawn_labels(&text, *n);
        let want: Vec<String> = expected.clone().map(|i| format!("opt-{i:02}")).collect();
        assert_eq!(drawn, want, "window mismatch for n={n} k={k}\n{text}");
    }
}

/// C6: a list that fits is drawn in full from index 0 (today's look), and
/// the popup shrinks to content height (oracle: 5 options + desc + 4 = 10).
#[test]
fn small_list_layout_unchanged() {
    let state = picker_state(opts(5), 2); // F5
    let text = render_text(80, 24, &state);
    let drawn = drawn_labels(&text, 5);
    assert_eq!(
        drawn,
        (0..5).map(|i| format!("opt-{i:02}")).collect::<Vec<_>>()
    );
    assert!(
        text.contains("desc-02"),
        "selected description missing\n{text}"
    );
    assert_eq!(
        popup_height(&text),
        10,
        "popup height != oracle literal 10\n{text}"
    );
}

/// C7: an empty filter result renders the frame + filter line, no marker,
/// no panic.
#[test]
fn empty_filter_no_panic() {
    let mut state = picker_state(opts(0), 0);
    state.filter = "zzz".into();
    let text = render_text(80, 24, &state);
    assert!(text.contains("Filter:"), "filter line missing\n{text}");
    assert!(
        !text.contains('▸'),
        "marker drawn with zero options\n{text}"
    );
}

/// C3: the selected option's description renders inside the popup on the
/// reserved row, and popup height is constant across every selection —
/// including when the selected option has NO description while others do
/// (the reserve keys off "any option has one", not "selected has one").
#[test]
fn description_contained_height_stable() {
    // All-desc list overflowing at 80x24: height literal 20 (oracle-v2).
    let heights: Vec<usize> = (0..20)
        .map(|k| {
            let state = picker_state(opts(20), k);
            let text = render_text(80, 24, &state);
            assert!(
                text.contains(&format!("desc-{k:02}")),
                "selected description missing at k={k}\n{text}"
            );
            popup_height(&text)
        })
        .collect();
    assert!(
        heights.iter().all(|&h| h == 20),
        "popup height jitters across selection: {heights:?}"
    );

    // Mixed: only opt-00 has a description. Height must not depend on
    // whether the SELECTED option has one.
    let mut mixed = opts(5);
    for opt in mixed.iter_mut().skip(1) {
        opt.description = None;
    }
    let h_desc_selected = popup_height(&render_text(80, 24, &picker_state(mixed.clone(), 0)));
    let h_plain_selected = popup_height(&render_text(80, 24, &picker_state(mixed, 4)));
    assert_eq!(
        h_desc_selected, h_plain_selected,
        "reserve-if-selected jitter bug: {h_desc_selected} vs {h_plain_selected}"
    );
}

/// C4: the scrollbar renders iff the list overflows the window — exact-fit
/// boundary included. (Display-only: no key-handling code changes; the
/// cyril binary crate is untouched by this feature.)
#[test]
fn scrollbar_iff_overflow() {
    // 80x24 gives 15 option rows (oracle-v2): n=15 fits exactly, n=16
    // overflows. ratatui 0.30's default vertical scrollbar caps are ▲/▼.
    let fits = render_text(80, 24, &picker_state(opts(15), 0));
    assert!(
        !fits.contains('▲') && !fits.contains('▼'),
        "scrollbar drawn on exact fit\n{fits}"
    );
    let overflows = render_text(80, 24, &picker_state(opts(16), 0));
    assert!(
        overflows.contains('▲') && overflows.contains('▼'),
        "scrollbar missing on overflow\n{overflows}"
    );
    // Caps are inset inside the border: corners survive.
    assert!(
        overflows.contains('┐') && overflows.contains('┘'),
        "scrollbar overdraws border corners\n{overflows}"
    );
}

/// The thumb spans the full track: selecting the last option puts it at
/// the bottom (a window-start-positioned thumb strands at (n-rows)/n).
#[test]
fn scrollbar_thumb_reaches_bottom_at_list_end() {
    let text = render_text(80, 24, &picker_state(opts(16), 15));
    let grid: Vec<Vec<char>> = text.lines().map(|l| l.chars().collect()).collect();
    let Some((y, x)) = grid
        .iter()
        .enumerate()
        .find_map(|(y, row)| row.iter().position(|&c| c == '▼').map(|x| (y, x)))
    else {
        panic!("no ▼ cap in overflow render\n{text}");
    };
    assert_eq!(
        grid[y - 1].get(x),
        Some(&'█'),
        "thumb not at track bottom with last option selected\n{text}"
    );
}

/// AC(a) "long *filtered* option list": a non-contiguous filtered subset
/// (every third option) windows in filtered space — the selection stays
/// visible and non-matching options never render.
#[test]
fn filtered_subset_keeps_selection_visible() {
    let filtered: Vec<usize> = (0..30).filter(|i| i % 3 == 0).collect(); // 10 entries
    let state = PickerState {
        title: "Fence".into(),
        options: opts(30),
        filter: "x".into(),
        filtered_indices: filtered,
        selected: 9, // deep in the filtered list -> option 27
    };
    let text = render_text(60, 16, &state); // floor: 7 rows, window [3,10)
    let Some(marker_line) = text.lines().find(|l| l.contains('▸')) else {
        panic!("selection invisible on filtered subset\n{text}");
    };
    assert!(
        marker_line.contains("opt-27"),
        "marker not on opt-27\n{text}"
    );
    let drawn = drawn_labels(&text, 30);
    let want: Vec<String> = [9, 12, 15, 18, 21, 24, 27]
        .iter()
        .map(|i| format!("opt-{i:02}"))
        .collect();
    assert_eq!(drawn, want, "filtered window mismatch\n{text}");
}

/// C5: at the 60x16 support floor with 15 described options, walking the
/// selection through every index via the REAL state machine keeps the
/// marker and the selected label on screen at every step, and the drawn
/// window matches the oracle literals (oracle-v2.py --walk).
#[test]
fn floor_60x16_full_walk() {
    // WALK literals from .cyril-cc5e/oracle-v2.py --walk (window starts).
    let expected_starts = [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8];
    let mut ui = cyril_ui::state::UiState::new(1000);
    ui.show_picker("Fence".into(), opts(15));
    for (k, &want_start) in expected_starts.iter().enumerate() {
        if k > 0 {
            ui.picker_select_next();
        }
        let Some(picker) = cyril_ui::traits::TuiState::picker(&ui) else {
            panic!("picker vanished at k={k}");
        };
        let text = render_text(60, 16, picker);
        let marker_line = text.lines().find(|l| l.contains('▸'));
        let Some(marker_line) = marker_line else {
            panic!("selection invisible at walk step k={k}\n{text}");
        };
        assert!(
            marker_line.contains(&format!("opt-{k:02}")),
            "marker not on opt-{k:02} at step {k}\n{text}"
        );
        let drawn = drawn_labels(&text, 15);
        let want: Vec<String> = (want_start..want_start + 7)
            .map(|i| format!("opt-{i:02}"))
            .collect();
        assert_eq!(drawn, want, "window mismatch at walk step k={k}\n{text}");
    }
}

/// C10: below-floor terminals render without panicking (content may clip).
#[test]
fn degenerate_sizes_no_panic() {
    for &(w, h) in &[(20u16, 8u16), (5, 5), (0, 0), (60, 5)] {
        let state = picker_state(opts(15), 14);
        let _ = render_text(w.max(1), h.max(1), &state);
    }
    // TestBackend cannot be 0x0, but the popup area can: prove the
    // arithmetic path directly at a 1x1 terminal (popup clamps to empty).
    let state = picker_state(opts(3), 2);
    let _ = render_text(1, 1, &state);
}

/// Stress: two options share a label — exactly one ▸ row, and it marks the
/// second occurrence (selection is positional, not label-matched).
#[test]
fn duplicate_labels_single_marker() {
    let dup = |cur| CommandOption {
        label: "dup".into(),
        value: "v".into(),
        description: None,
        group: None,
        is_current: cur,
    };
    let state = picker_state(vec![dup(true), dup(false)], 1);
    let text = render_text(80, 24, &state);
    assert_eq!(text.matches('▸').count(), 1, "marker count != 1\n{text}");
    let marked: Vec<usize> = text
        .lines()
        .enumerate()
        .filter(|(_, l)| l.contains('▸'))
        .map(|(y, _)| y)
        .collect();
    let dup_rows: Vec<usize> = text
        .lines()
        .enumerate()
        .filter(|(_, l)| l.contains("dup"))
        .map(|(y, _)| y)
        .collect();
    assert_eq!(dup_rows.len(), 2, "expected two dup rows\n{text}");
    assert_eq!(
        marked,
        vec![dup_rows[1]],
        "marker not on second dup row\n{text}"
    );
}
